module.exports = [
	{
		id: 0,
		homeTeam: 'Man City',
		awayTeam: 'Liverpool',
		date: '2021. 11. 29.',
		homeScore: undefined,
		awayScore: undefined,
	},
	{
		id: 1,
		homeTeam: 'Barcelona',
		awayTeam: 'Bayern',
		date: '2021. 11. 22.',
		homeScore: undefined,
		awayScore: undefined,
	},
	{
		id: 2,
		homeTeam: 'Spurs',
		awayTeam: 'Man Utd',
		date: '2021. 11. 14.',
		homeScore: undefined,
		awayScore: undefined,
	},
	{
		id: 3,
		homeTeam: 'Man City',
		awayTeam: 'Liverpool',
		date: '2021. 09. 19',
		homeScore: 0,
		awayScore: 1,
	},
	{
		id: 4,
		homeTeam: 'Barcelona',
		awayTeam: 'Bayern',
		date: '2021. 10. 19',
		homeScore: 3,
		awayScore: 1,
	},
	{
		id: 5,
		homeTeam: 'Spurs',
		awayTeam: 'Man Utd',
		date: '2021. 05. 19',
		homeScore: 1,
		awayScore: 1,
	},
	{
		id: 6,
		homeTeam: 'Barcelona',
		awayTeam: 'Man Utd',
		date: '2021. 05. 19',
		homeScore: 4,
		awayScore: 1,
	},
];
